# Mermaid to Image Conversion Configuration
# This file contains default settings for converting Mermaid diagrams to high-quality images

# Output directory for generated images (relative to project root)
output_dir: "visualizations"

# Image format: png, svg, or pdf
# - png: Best for high-resolution raster output, good for documents and presentations
# - svg: Best for scalable vector graphics, ideal for web and print
# - pdf: Good for documents, vector format with text support
image_format: "png"

# Image dimensions (applies to PNG format only)
# Standard resolutions:
# - 1920x1080 (Full HD)
# - 2560x1440 (2K)
# - 3840x2160 (4K)
width: 1920
height: 1080

# DPI/Resolution for high-quality output
# - 72: Web/screen display
# - 150: Good quality for most uses
# - 300: Print quality
# - 600-1200: High-quality print/professional use
dpi: 600

# Background color (for PNG format)
# Options: "white", "transparent", or any valid CSS color
background_color: "white"

# Mermaid theme
# Options: "default", "dark", "forest", "neutral"
theme: "neutral"

# Scale factor for higher resolution rendering
# - 1: Standard resolution
# - 2: 2x resolution (recommended for high-quality)
# - 3: 3x resolution (very high quality, larger files)
scale: 3

# Timeout for diagram rendering (in milliseconds)
# Increase if complex diagrams are timing out
timeout: 30000

# Advanced settings (future use)
# retry_count: 3  # Number of retry attempts
# cache_images: true  # Cache generated images to avoid regeneration

# 10-K SEC Filing Analysis Configuration
# Settings for extracting technology-related sections from 10-K filings
sec_10k:
  # Output directory for processed 10-K markdown files
  output_dir: "markdown"
  
  # Temporary directory for downloading HTML files
  temp_dir: "temp"
  
  # SEC API settings
  api:
    # Base URL for SEC data API
    base_url: "https://data.sec.gov"
    
    # Request timeout in seconds
    timeout: 30
    
    # Rate limiting (requests per second)
    rate_limit: 8  # Conservative limit (SEC allows 10/sec)
    
    # User agent string for SEC API requests (Required format: Company Name Contact@domain.com)
    user_agent: "Claude Code Analyst sehgal.manav@gmail.com"
  
  # Technology-relevant 10-K sections to extract
  # These sections typically contain technology strategy and business needs
  sections:
    # Item 1: Business Description
    - item: "1"
      title: "Business"
      patterns:
        - "item\\s*1[^a-z]*business"
        - "part\\s*i.*item\\s*1[^a-z]*business"
      description: "Core business operations, technology infrastructure, and market positioning"
    
    # Item 1A: Risk Factors (especially cybersecurity and technology risks)
    - item: "1A"
      title: "Risk Factors"
      patterns:
        - "item\\s*1a[^a-z]*risk\\s*factors"
        - "part\\s*i.*item\\s*1a[^a-z]*risk\\s*factors"
      description: "Technology risks, cybersecurity threats, and strategic vulnerabilities"
    
    # Item 2: Properties (technology infrastructure, data centers, etc.)
    - item: "2"
      title: "Properties"
      patterns:
        - "item\\s*2[^a-z]*properties"
        - "part\\s*i.*item\\s*2[^a-z]*properties"
      description: "Physical and technology infrastructure, facilities, and assets"
    
    # Item 7: Management Discussion & Analysis (technology investments, strategy)
    - item: "7"
      title: "Management's Discussion and Analysis"
      patterns:
        - "item\\s*7[^a-z]*management.*discussion"
        - "part\\s*ii.*item\\s*7[^a-z]*management.*discussion"
      description: "Strategic technology investments, digital transformation, and future plans"
  
  # Content filtering settings
  filtering:
    # Minimum section length (words) to include
    min_section_length: 100
    
    # Maximum section length (words) to process 
    max_section_length: 50000
    
    # Technology-related keywords to prioritize content
    tech_keywords:
      - "technology"
      - "digital"
      - "software"
      - "cybersecurity"
      - "artificial intelligence"
      - "machine learning" 
      - "cloud computing"
      - "data analytics"
      - "automation"
      - "infrastructure"
      - "platform"
      - "innovation"
      - "research and development"
      - "intellectual property"